141 melhoria atualização automática do zoom
CMCuritiba/Estacao-Trabalho-CMC pull request #142
Opened 2024-02-09 13:52 UTC by lucasdeabreufonseca

**Descrição do Merge Request**

- O que há de novo?
 -Script de atualização automática do zoom

Resolves: #141 

**Checklist**

- [x] Eu rodei este código localmente
- [ ] Eu escrevi os testes necessários
- [ ] Eu utilizei _type-hints_ em meu código
- [ ] Eu não deixei dados _hard-coded_ em meu código
- [ ] Eu atualizei o CHANGELOG/README

**Recursos adicionais**

https://github.com/pazepaze/zoom-autoupdater/tree/master

**Considerações adicionais**

-Nenhum

2024-02-09 20:38 UTC, brunosoli requested changes
Este script pode ser copiado para o repo [CMCuritiba/iac-automacao](https://github.com/CMCuritiba/iac-automacao) para aplicar nas estações de trabalho em produção.

2024-02-09 20:38 UTC, brunosoli commented on arquivos/zoom-autoupdate.sh
Este script não deve ficar na pasta `arquivos`, deve ficar entre os scripts principais.

2024-02-09 20:38 UTC, brunosoli commented on arquivos/zoom-autoupdate.sh
> +    cat <<'EOF' >/opt/zoom-updater/zoom-update.sh
Uma sugestão de melhores práticas é criar o arquivo `arquivos/zoom-update.sh` e aqui neste script apenas copiar o fonte para o destino na estação de trabalho.

2024-02-09 20:38 UTC, brunosoli commented on arquivos/zoom-autoupdate.sh
> +  cat <<'EOF' >/etc/systemd/system/zoom-update.service
Mesma coisa aqui.

2024-02-15 13:59 UTC, lucasdeabreufonseca commented
criei o arquivo de serviço e o script de atualização na pasta arquivos e adicionei o script que cria o instalador na pasta de scripts gerais

2024-02-15 17:22 UTC, brunosoli commented
> criei o arquivo de serviço e o script de atualização na pasta arquivos e adicionei o script que cria o instalador na pasta de scripts gerais

Você não comitou o arquivo `arquivos/zoom-update.service`?

2024-02-15 17:33 UTC, brunosoli requested changes

2024-02-15 17:33 UTC, brunosoli commented on scripts/211-zoom-autoupdate.sh
> +   cp ../arquivos/zoom-update.sh /opt/zoom-updater
```suggestion
if [ -f "../arquivos/zoom-autoupdate.sh" ]; then
   cp "../arquivos/zoom-autoupdate.sh" /usr/local/cmc/zoom-updater.sh
   chmod +x /usr/local/cmc/zoom-updater.sh
```

No arquivo `arquivos/zoom-update.service` você vai precisar atualizar o caminho do executável para `/usr/local/cmc/zoom-updater.sh`.

Por fim, cê vai precisar adicionar um link simbólico para o `/usr/local/cmc/zoom-updater.sh` lá no script `999`.

2024-02-15 17:33 UTC, brunosoli commented on scripts/211-zoom-autoupdate.sh
> +   exit
```suggestion
   exit 1
```

2024-02-15 17:33 UTC, brunosoli commented on scripts/211-zoom-autoupdate.sh
> +   exit
```suggestion
   exit 1
```

2024-02-16 11:51 UTC, lucasdeabreufonseca commented
alterações feitas como solicitado.

2024-02-16 18:33 UTC, brunosoli commented
Aguardando o @lucasdeabreufonseca implementar a execução periódica (diária?) da atualização.

Possível link útil: https://unix.stackexchange.com/a/198450

2024-02-21 14:30 UTC, brunosoli approved these changes

2024-02-21 14:36 UTC, merged